Nome: Ana Laura Angelieri       BP3038262

Código feito no Google Colab

In [ ]:
import numpy as np

Exercício 1:
Crie um array NumPy com o número 1000000 e uma lista com o número 1000000.
Multiplique cada elemento do array e da lista por 2 e calcule o tempo de
execução com cada um dos objetos (use %time).
Qual objeto oferece melhor performance, array NumPy ou lista?

In [ ]:
array = np.arange(1000000)
lista = list(range(1000000))

%time tempoArray = array * 2
%time tempoLista = [x * 2 for x in lista]

#O objeto que oferece melhor performance é o array

CPU times: user 18 µs, sys: 10.5 ms, total: 10.5 ms
Wall time: 10.5 ms
CPU times: user 51.1 ms, sys: 96.4 ms, total: 148 ms
Wall time: 147 ms


Exercício 2:
Crie um array numpy de 10 elementos
Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [ ]:
array2 = np.arange(10)
array2[5:9] = 0
print(array2)

[0 1 2 3 4 0 0 0 0 9]


Exercício 3: Crie um array numpy de 3 dimensões e imprima a dimensão 1

In [ ]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 9, 8]], [[7, 6, 5], [4, 3, 2]]])
print(array3d[0])
# array3d.ndim

[[1 2 3]
 [4 5 6]]


Exercício 4: Crie um array numpy de duas dimensões (matriz).
Imprima os elementos da terceira linha da matriz
Imprima todos os elementos da primeira e segunda linhas e segunda
e terceira colunas

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Imprimindo a terceira linha da matriz')
print(matriz[2])

print('Imprimindo elementos primeira e segunda linhas')
print(matriz[0:2])

print('Imprimindo elementos da segunda e terceira colunas')
print(matriz[:, 1:3])

print('Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas')
print(matriz[0:2, 1:3])

Imprimindo a terceira linha da matriz
[7 8 9]
Imprimindo elementos primeira e segunda linhas
[[1 2 3]
 [4 5 6]]
Imprimindo elementos da segunda e terceira colunas
[[2 3]
 [5 6]
 [8 9]]
Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
[[2 3]
 [5 6]]


Exercício 5: Crie uma matriz de 15 números com 3 linhas 5 colunas utilizando numpy
Utilize o métodos arange() para criar a matriz e reshape() para dimensioná-la
Em seguida, calcule a matriz transposta dessa matriz.

In [ ]:
matriz2 = np.arange(15).reshape(3,5)
matriz2transposta = matriz2.T

print('Matriz original')
print(matriz2)

print('Matriz transposta')
print(matriz2transposta)

Matriz original
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Matriz transposta
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


Exercício 6: Considere os 3 arrays abaixo
Retorne o valor do array xarr se o valor for True no array cond.
Caso contrário, retorne o valor do array yarr.

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

resultado = np.where(cond, xarr, yarr)
print(resultado)

[1.1 2.2 1.3 1.4 2.5]


Exercício 7: Crie um array A com 10 elementos e salve o array em disco com a extensão npy.
O arqquivo .npy é utilizado para armazenar arrays do NumPy (numpy.ndarray)
de forma eficiente preservando os dados e o formato do array.
Depois carregue o array do disco no array B.

In [ ]:
A = np.arange(10)
np.save('ArrayA.npy', A)

B = np.load('ArrayA.npy')

print('Array A:')
print(A)

print('Array B: ')
print(B)

Array A:
[0 1 2 3 4 5 6 7 8 9]
Array B: 
[0 1 2 3 4 5 6 7 8 9]


Exercício 8: Considerando a série abaixo, imprima os valores únicos na série, ou seja,
aqueles que não se repetem.

In [ ]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.value_counts()[obj.value_counts() == 1]


d    1
Name: count, dtype: int64

Exercício 9: O trecho de código a seguir, conecta em uma url na internet,
que acessa e baixa um dataset da internet.
Exiba os dados das colunas 'number', 'title', 'labels', 'state'
do dataframe conforme a seguir.

In [ ]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
dados = resp.json()
df = pd.DataFrame(dados)
print(df[['number', 'title', 'labels', 'state']])

    number                                              title  \
0    61382  BUG: Multindex difference not working on colum...   
1    61381  Fix alignment in Series subtraction with Multi...   
2    61380  Update CI to include Translations from Scienti...   
3    61378  DOC: update pandas cheat sheet with a third pa...   
4    61372           Fix pyarrow comparison issue in array.py   
5    61370                         ENH: Adding hint to to_sql   
6    61368        BUG: Python 3.14 may not increment refcount   
7    61365  BUG: Constructing series with Timedelta object...   
8    61363  DOC: Added constructor parameters to DateOffse...   
9    61362  QST: best way to extend/subclass pandas.DataFrame   
10   61359  BUG: Raise ValueError for non-string columns i...   
11   61358  Improve documentation for MonthEnd and YearBeg...   
12   61357  DOC: change `tuples` param for MultiIndex.from...   
13   61353  BUG: inserting list of strings into Series aut...   
14   61351  Add warning t

Exercício 10: Crie um dicionário python com 5 linguagens, de programação,
a quantidade de usuários dessas linguagens nos estados unidos
e o ano de lançamento de cada uma delas, onde, a chave serão
as linguagens de programação e os valores como listas python
desse dicionário.
linguagens: Python, JavaScript, Java, C#, C++
Ano de Lançamento: 1991, 1995, 1995, 2000, 1985
Qtde. Usuários: 8000000, 7500000, 5000000, 3000000, 2500000

In [ ]:
linguagens = {
    'Python': [1991, 8000000],
    'JavaScript': [1995, 7500000],
    'Java': [1995, 5000000],
    'C#': [2000, 3000000],
    'C++': [1985, 2500000]
}

In [ ]:
# Converta o dicionário em um dataframe
df = pd.DataFrame.from_dict(linguagens)
print(df)

    Python  JavaScript     Java       C#      C++
0     1991        1995     1995     2000     1985
1  8000000     7500000  5000000  3000000  2500000


In [ ]:
# Converta no dataframe linhas em colunas e colunas em linhas.
df = df.T
print(df)

               0        1
Python      1991  8000000
JavaScript  1995  7500000
Java        1995  5000000
C#          2000  3000000
C++         1985  2500000


In [ ]:
# Altere os títulos das colunas para Qtde Usuarios e Ano
df = df.rename(columns={0: 'Ano', 1: 'Qde Usuarios'}, )
print(df)

             Ano  Qde Usuarios
Python      1991       8000000
JavaScript  1995       7500000
Java        1995       5000000
C#          2000       3000000
C++         1985       2500000


In [ ]:
# Exiba o tipo de dado de cada coluna.
df.dtypes

Ano             int64
Qde Usuarios    int64
dtype: object

In [ ]:
# Visualize as 5 primeiras linhas do dataframe
df.head()

Ano  Qde Usuarios
Python      1991       8000000
JavaScript  1995       7500000
Java        1995       5000000
C#          2000       3000000
C++         1985       2500000

Exercício 11: Usando o método read_csv do pandas e carregue o arquivo salarios.csv
Este método exige-se que se coloque o separador vírgula ','
no parâmetro sep.

In [ ]:
#célula porque fiz o código no google colab
#from google.colab import files

#uploaded = files.upload()

Saving salarios.csv to salarios.csv


In [ ]:
df = pd.read_csv('salarios.csv', sep = ',')

In [ ]:
# Verifique se as colunas do dataframe possuem valores ausentes.
df.isna().sum()

NameError: name 'df' is not defined

In [ ]:
# Remova do datafrane a linha cujo índice é o número 32181
df.drop(32181)

Name                  Position Title        Department  \
0          AARON,  ELVIA J                WATER RATE TAKER       WATER MGMNT   
1        AARON,  JEFFERY M                  POLICE OFFICER            POLICE   
2           AARON,  KARINA                  POLICE OFFICER            POLICE   
3      AARON,  KIMBERLEI R        CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4      ABAD JR,  VICENTE M               CIVIL ENGINEER IV       WATER MGMNT   
...                    ...                             ...               ...   
32176  ZYGADLO,  MICHAEL J  FRM OF MACHINISTS - AUTOMOTIVE  GENERAL SERVICES   
32177   ZYGOWICZ,  PETER J                  POLICE OFFICER            POLICE   
32178    ZYMANTAS,  MARK E                  POLICE OFFICER            POLICE   
32179  ZYRKOWSKI,  CARLO E                  POLICE OFFICER            POLICE   
32180  ZYSKOWSKI,  DARIUSZ         CHIEF DATA BASE ANALYST              DoIT   

       Employee Annual Salary  
0                     88968.0  
1                     80778.0  
2                     80778.0  
3                     84780.0  
4                    104736.0  
...                       ...  
32176                 97448.0  
32177                 86520.0  
32178                 83616.0  
32179                 86520.0  
32180                110352.0  

[32181 rows x 4 columns]

In [ ]:
# Exiba os tipos de dados de cada coluna do dataframe
df.dtypes

Name                      object
Position Title            object
Department                object
Employee Annual Salary    object
dtype: object

In [ ]:
# Remova o caractere $ dos valores da coluna Employee Annual Salary e
# Converta a coluna Employee Annual Salary para tipo float.
df['Employee Annual Salary'] = df['Employee Annual Salary'].str.replace('$', '')
df['Employee Annual Salary'] = df['Employee Annual Salary'].astype(float)

In [ ]:
# Faça a somatória da coluna Employee Annual Salary
salarioTotal = df['Employee Annual Salary'].sum()
print(salarioTotal)

2547690152.24
